// Generated by CoffeeScript 1.7.1

/*
  Helper to use @module "foo", -> notation
 */

(function() {
  window.module = function(name, fn) {
    if (this[name] == null) {
      this[name] = {};
    }
    if (this[name].module == null) {
      this[name].module = window.module;
    }
    return fn.apply(this[name], []);
  };

}).call(this);

//# sourceMappingURL=moduleHelper.js.map